name: Continuous Delivery
on:
  pull_request:
    branches:
      - main
jobs:
  deliver:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          # Adicione seus comandos de teste aqui
          pytest
      - name: Simulation CD
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            '**/*.py'
            README.md

  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest
